# Generated by Django 3.1 on 2022-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
