# Generated by Django 4.0.6 on 2022-07-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_videopost_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
